---

db.options:
  driver: pdo_mysql
  host: 127.0.0.1
  port: 3306
  dbname: gemini
  user: changeme
  password: changeme

log:
  # Valid log levels are:
  # DEBUG, INFO, NOTICE, WARNING, ERROR, CRITICAL, ALERT, EMERGENCY, NONE
  # log level none won't open logfile
  level: DEBUG
  file: ../gemini.log

security:
  # toggles JWT security for service
  enable: false
  # Path to the syn config file for authentication.
  # example can be found here:
  # https://github.com/Islandora-CLAW/Syn/blob/master/conf/syn-settings.example.xml
  config: ../syn-settings.xml